// Maps every item and creature to a bundled game-icons.net icon (CC BY 3.0,
// authors listed in the README) so each entry always has a real illustration,
// fully offline. Keyword tables match the Italian names; category/type
// fallbacks guarantee full coverage.

const files = import.meta.glob('../assets/game-icons/*.svg', { eager: true, query: '?url', import: 'default' });

function url(name) {
  return files[`../assets/game-icons/${name}.svg`];
}

const WEAPON_KEYWORDS = [
  [/ascia|scure/, 'battle-axe'],
  [/balestra/, 'crossbow'],
  [/\barco\b/, 'bow-arrow'],
  [/pugnal|stiletto|coltell/, 'plain-dagger'],
  [/mazzafrust/, 'flail'],
  [/morning|stella del mattino/, 'spiked-ball'],
  [/martello|maglio/, 'warhammer'],
  [/\bmazza\b/, 'mace-head'],
  [/alabarda|glaivo|falcione/, 'halberd'],
  [/tridente/, 'trident'],
  [/lancia|picca|giavellotto/, 'barbed-spear'],
  [/falce/, 'scythe'],
  [/frusta/, 'whip'],
  [/randello|clava/, 'wood-club'],
  [/bastone ferrato/, 'bo'],
  [/fionda/, 'sling'],
  [/piccone/, 'war-pick'],
  [/\brete\b/, 'fishing-net'],
  [/scimitarra|sciabola/, 'crescent-blade'],
  [/spada corta|stocco|fioretto/, 'gladius'],
  [/spada|spadone|lama\b/, 'broadsword'],
  [/freccetta|dardo/, 'heavy-arrow'],
  [/cerbottana|bastone/, 'bo'],
];

const AMMUNITION_KEYWORDS = [
  [/frecc|quadrell|dardo/, 'heavy-arrow'],
  [/proiettil|pallottol/, 'marbles'],
  [/faretra/, 'quiver'],
];

const ARMOR_KEYWORDS = [
  [/scudo/, 'checked-shield'],
  [/maglia/, 'chain-mail'],
  [/scagli/, 'scale-mail'],
  [/cuoio|pelle|imbottita/, 'leather-vest'],
  [/mezza armatura|lamell/, 'lamellar'],
  [/elmo|elmetto/, 'visored-helm'],
];

const WONDROUS_KEYWORDS = [
  [/corona|diadema/, 'jewel-crown'],
  [/amuleto|medaglione|ciondolo|collana|pendente|talismano/, 'gem-pendant'],
  [/mantello|manto|cappa|tabarro/, 'cape'],
  [/stivali|scarpe|calzari/, 'boots'],
  [/guanti|bracciali|manopol/, 'gauntlet'],
  [/cintura|fibbia|cinghia/, 'belt'],
  [/borsa|sacco|sacchetto|marsupio|zainetto/, 'swap-bag'],
  [/zaino/, 'backpack'],
  [/tappeto/, 'red-carpet'],
  [/scopa/, 'magic-broom'],
  [/candela/, 'candlebright'],
  [/campan/, 'bell-shield'],
  [/specchio/, 'mirror-mirror'],
  [/\bcorno\b/, 'hunting-horn'],
  [/sfera di cristallo|sfera|globo/, 'crystal-ball'],
  [/spilla|fermaglio/, 'gem-chain'],
  [/lente|monocolo|occhiali/, 'magnifying-glass'],
  [/libro|tomo|grimorio|manuale/, 'book-cover'],
  [/statuetta|figurina/, 'colombian-statue'],
  [/gemma|diamante|perla|gioiello/, 'cut-diamond'],
  [/fune|corda/, 'rope-coil'],
  [/bottiglia|caraffa|otre|decanter/, 'bottle-vapors'],
  [/braciere/, 'fire-bowl'],
  [/incensiere|turibolo/, 'incense'],
  [/elmo|elmetto/, 'visored-helm'],
  [/faretra/, 'quiver'],
  [/cubo/, 'cube'],
  [/occhio|occhi\b/, 'eyeball'],
  [/piuma|penna\b/, 'feather'],
  [/scarabeo|scaraboide/, 'gem-chain'],
  [/polvere/, 'powder-bag'],
  [/strumento|liuto|flauto/, 'lyre'],
  [/pozione|filtro|elisir|unguento/, 'standing-potion'],
  [/anello/, 'ring'],
  [/manette|bande di ferro/, 'manacles'],
  [/mazzo/, 'card-random'],
  [/barca/, 'canoe'],
  [/travestimento/, 'carnival-mask'],
  [/ferri d/, 'horseshoe'],
  [/fortezza/, 'stone-tower'],
  [/fiasco|boccale/, 'bottle-vapors'],
  [/lanterna/, 'lantern-flame'],
  [/pigmenti|colori scintillanti/, 'paint-brush'],
  [/periapto/, 'gem-pendant'],
  [/veste|tonaca|abito/, 'cape'],
  [/pantofole/, 'boots'],
  [/\bali\b/, 'angel-wings'],
  [/ventaglio/, 'feather'],
  [/cub(o|ico)/, 'cube'],
  [/ciotola|calderone/, 'cauldron'],
  [/colla|solvente/, 'corked-tube'],
  [/sacca/, 'swap-bag'],
];

const GEAR_KEYWORDS = [
  [/zaino/, 'backpack'],
  [/corda|fune/, 'rope-coil'],
  [/acqua santa|acquasanta/, 'holy-water'],
  [/fiala|ampolla|boccetta/, 'corked-tube'],
  [/bottiglia|caraffa/, 'bottle-vapors'],
  [/otre|borraccia/, 'waterskin'],
  [/cassa|forziere|baule|scrigno/, 'locked-chest'],
  [/tenda/, 'camping-tent'],
  [/scala\b/, 'ladder'],
  [/torcia/, 'torch'],
  [/lanterna|lampada/, 'lantern-flame'],
  [/candela/, 'candlebright'],
  [/sacco a pelo/, 'sleeping-bag'],
  [/coperta/, 'blanket'],
  [/amo da pesca|amo\b|pesca/, 'fishing-hook'],
  [/\brete\b/, 'fishing-net'],
  [/rampino/, 'grapple'],
  [/cannocchiale/, 'spyglass'],
  [/inchiostro|penna|pennino/, 'quill-ink'],
  [/manette|catena/, 'manacles'],
  [/piede di porco/, 'crowbar'],
  [/badile|pala\b|vanga/, 'trench-spade'],
  [/piccone/, 'war-pick'],
  [/martello|mazzuolo/, 'flat-hammer'],
  [/chiod|piton/, 'flat-hammer'],
  [/specchio|specchietto/, 'mirror-mirror'],
  [/olio/, 'corked-tube'],
  [/acciarino|pietra focaia/, 'flint-spark'],
  [/veleno/, 'skull-in-jar'],
  [/razioni|cibo/, 'bread'],
  [/libro|tomo/, 'book-cover'],
  [/simbolo sacro/, 'ankh'],
  [/guaritore|bende/, 'bandage-roll'],
  [/triboli/, 'caltrops'],
  [/fuoco dell'alchimista/, 'molotov'],
  [/sapone/, 'holy-water'],
  [/campan/, 'gong'],
  [/fischietto/, 'whistle'],
  [/abaco/, 'abacus'],
  [/clessidra/, 'hourglass'],
  [/bilancia/, 'libra'],
  [/barile|botte\b/, 'barrel'],
  [/cesto|cesta|paniere/, 'basket'],
  [/secchio/, 'barrel'],
  [/mappa|pergamena|carta\b/, 'treasure-map'],
  [/bussola/, 'compass'],
  [/sfere metalliche|biglie/, 'marbles'],
  [/sale\b/, 'salt-shaker'],
  [/polvere/, 'powder-bag'],
  [/borsa|sacco|sacchetto/, 'swap-bag'],
  [/gessetto|gesso/, 'chisel'],
  [/vestiti|abito|costume|tonaca|paramenti/, 'cape'],
  [/paletto|palo\b|asta\b/, 'bo'],
  [/lente/, 'magnifying-glass'],
  [/mortaio|pestello/, 'pestle-mortar'],
  [/amuleto|emblema|reliquiario|totem/, 'ankh'],
  [/freccia|dardo|proiettile/, 'heavy-arrow'],
  [/custodia per dardi|faretra/, 'quiver'],
  [/custodia per mappe/, 'treasure-map'],
  [/carrucola|spago/, 'rope-coil'],
  [/kit da scalatore/, 'grapple'],
  [/picchetto|ariete/, 'flat-hammer'],
  [/incens/, 'incense'],
  [/cristallo/, 'floating-crystal'],
  [/sfera/, 'crystal-ball'],
  [/kit da travestimento/, 'carnival-mask'],
  [/kit da contraffattore/, 'quill-ink'],
  [/kit di erborista/, 'pestle-mortar'],
  [/kit da avvelenatore/, 'skull-in-jar'],
  [/kit da campo|pentola/, 'cauldron'],
  [/fiasco|brocca|boccale/, 'bottle-vapors'],
  [/lucchetto|cassetta/, 'locked-chest'],
  [/bacchetta/, 'crystal-wand'],
  [/bastone magico/, 'wizard-staff'],
  [/bastone/, 'bo'],
  [/ceralacca/, 'candlebright'],
  [/anello/, 'ring'],
  [/coltello/, 'plain-dagger'],
  [/rametto|vischio/, 'curling-vines'],
  [/pietra per affilare|gessetto|gesso/, 'chisel'],
  [/ago\b/, 'sewing-needle'],
];

const TOOLS_KEYWORDS = [
  [/fabbro/, 'anvil'],
  [/falegname|carpentiere/, 'hand-saw'],
  [/alchimista|erborista/, 'pestle-mortar'],
  [/pittore/, 'paint-brush'],
  [/tessitore|sarto|calzolaio|conciatore/, 'sewing-needle'],
  [/cuoco/, 'cauldron'],
  [/intagliatore|scalpellino|muratore/, 'chisel'],
  [/riparatore|inventore/, 'gears'],
  [/gioielliere/, 'cut-diamond'],
  [/cartografo/, 'treasure-map'],
  [/calligrafo/, 'quill-ink'],
  [/navigatore/, 'ship-wheel'],
  [/avvelenatore/, 'skull-in-jar'],
  [/scass|grimaldell|ladro/, 'lockpicks'],
  [/cucina/, 'cauldron'],
  [/soffiatore/, 'bottle-vapors'],
  [/meccanico/, 'gears'],
  [/travestiment|camuffament/, 'carnival-mask'],
  [/contraffazione|falsari/, 'quill-ink'],
  [/dadi/, 'dice-six-faces-five'],
  [/carte/, 'card-random'],
  [/cornamusa|zampogna/, 'bagpipes'],
  [/tamburo/, 'drum'],
  [/flauto di pan/, 'pan-flute'],
  [/flauto/, 'flute'],
  [/lira\b/, 'lyre'],
  [/liuto|chitarra/, 'guitar'],
  [/viola|violino/, 'violin'],
  [/salterio|cetra|arpa/, 'lyre'],
  [/\bcorno\b|tromba/, 'hunting-horn'],
  [/vetraio|birraio|vasaio/, 'cauldron'],
];

const MOUNTS_KEYWORDS = [
  [/sella|bardatura|finimenti|morso|briglie/, 'saddle'],
  [/cavallo|destriero|ronzino|pony|cavalcatura/, 'horse-head'],
  [/mulo|asino/, 'donkey'],
  [/cammello/, 'camel'],
  [/elefante/, 'elephant'],
  [/carro|carrozza|slitta|calesse|diligenza/, 'old-wagon'],
  [/galea|nave|veliero|drakkar/, 'galleon'],
  [/barca|canoa|zattera|chiatta|chiglia/, 'canoe'],
  [/biga/, 'old-wagon'],
  [/mastino|cane/, 'wolf-howl'],
  [/timone/, 'ship-wheel'],
];

const CATEGORY_TABLES = {
  Weapon: WEAPON_KEYWORDS,
  Ammunition: AMMUNITION_KEYWORDS,
  Armor: ARMOR_KEYWORDS,
  'Wondrous Items': WONDROUS_KEYWORDS,
  'Adventuring Gear': GEAR_KEYWORDS,
  Tools: TOOLS_KEYWORDS,
  'Mounts and Vehicles': MOUNTS_KEYWORDS,
};

const CATEGORY_FALLBACKS = {
  Weapon: 'broadsword',
  Ammunition: 'quiver',
  Armor: 'breastplate',
  'Wondrous Items': 'floating-crystal',
  Ring: 'ring',
  Rod: 'winged-scepter',
  Potion: 'standing-potion',
  Scroll: 'tied-scroll',
  Staff: 'wizard-staff',
  Wand: 'crystal-wand',
  'Adventuring Gear': 'knapsack',
  Tools: 'toolbox',
  'Mounts and Vehicles': 'horse-head',
};

// Bespoke icons for the curated homebrew creatures (by lowercase name).
const CREATURE_NAME_ICONS = {
  'sciacallo di brace': 'wolf-howl',
  'spina cantante': 'cactus',
  "guardiano d'argilla": 'golem-head',
  'strige lunare': 'evil-bat',
  "ondina dell'abisso nero": 'sea-serpent',
  'custode delle rovine stellari': 'moai',
  'spettro del faro': 'ghost',
  'diavoletto dei contratti': 'imp-laugh',
  'serpe di vetro': 'rattlesnake',
  'colosso di radici': 'curling-vines',
  'cantastorie di bruma': 'hooded-figure',
  "melma dell'eco": 'dripping-goo',
};

const CREATURE_TYPE_ICONS = {
  aberration: 'brain-tentacle',
  beast: 'bear-head',
  celestial: 'angel-wings',
  construct: 'metal-golem-head',
  dragon: 'dragon-head',
  elemental: 'fire-silhouette',
  fey: 'fairy',
  fiend: 'devil-mask',
  giant: 'ogre',
  humanoid: 'cowled',
  monstrosity: 'hydra',
  ooze: 'acid-blob',
  plant: 'carnivorous-plant',
  undead: 'death-skull',
  'swarm of Tiny beasts': 'bee',
};

// kind: an item category or a creature type. Returns a bundled icon URL, or
// null only for unknown kinds (neither item category nor creature type).
export function iconFor(kind, name) {
  const n = (name || '').toLowerCase();
  const byCreatureName = CREATURE_NAME_ICONS[n];
  if (byCreatureName) return url(byCreatureName);

  const table = CATEGORY_TABLES[kind];
  if (table) {
    for (const [re, icon] of table) {
      if (re.test(n)) return url(icon);
    }
  }
  const fallback = CATEGORY_FALLBACKS[kind] || CREATURE_TYPE_ICONS[kind];
  return fallback ? url(fallback) : null;
}
