// Original homebrew creatures and magic items, authored from scratch for
// this project (not derived from or copying any published statblock/item).
// Added to broaden the bestiary/compendio beyond the translated SRD content,
// per the project's "SRD tradotta + homebrew originale" sourcing decision
// (no scraping of copyrighted third-party compendia). Stable, human-readable
// ids so re-seeding is idempotent.

export const HOMEBREW_CREATURES = [
  {
    id: 'hb-sciacallo-di-brace',
    name: 'Sciacallo di Brace',
    size: 'Small',
    type: 'beast',
    subtype: null,
    alignment: 'non allineato',
    ac: 13,
    hp: 7,
    hit_dice: '2d6',
    speed: { camminare: '12 m' },
    str: 8, dex: 15, con: 11, intl: 3, wis: 12, cha: 6,
    saving_throws: {},
    skills: { Percezione: 3 },
    damage_vulnerabilities: [],
    damage_resistances: [],
    damage_immunities: ['fuoco'],
    condition_immunities: [],
    senses: { scurovisione: '18 m', 'Percezione passiva': 13 },
    languages: '',
    cr: 0.125, xp: 25, proficiency_bonus: 2,
    traits: [
      { name: 'Fiuto Acuto', desc: 'Lo sciacallo ha vantaggio alle prove di Saggezza (Percezione) che si basano sull\'olfatto.' },
      { name: 'Pelle Incandescente', desc: 'Una creatura che colpisce lo sciacallo con un attacco in mischia mentre non indossa guanti o protezioni adeguate subisce 1 danno da fuoco.' },
    ],
    actions: [
      { name: 'Morso', desc: 'Attacco con Arma da Mischia: +4 per colpire, raggio 1,5 m, un obiettivo. Colpito: 4 (1d4 + 2) danni perforanti più 1 (1d4) danni da fuoco.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['deserto', 'collina'],
    image_url: null,
    description: 'Lo sciacallo di brace è un predatore delle terre aride il cui mantello arso scintilla come carbone ardente. Caccia in piccoli branchi notturni, attratto dal calore dei fuochi da campo, e la sua pelle resta calda al tatto molto tempo dopo la sua morte. Creatura di taglia Piccola, di tipo bestia, non allineata. Grado di Sfida 1/8.',
  },
  {
    id: 'hb-spina-cantante',
    name: 'Spina Cantante',
    size: 'Medium',
    type: 'plant',
    subtype: null,
    alignment: 'non allineato',
    ac: 12,
    hp: 22,
    hit_dice: '4d8+4',
    speed: { camminare: '3 m' },
    str: 14, dex: 8, con: 14, intl: 4, wis: 13, cha: 11,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: ['fuoco'],
    damage_resistances: [],
    damage_immunities: [],
    condition_immunities: [],
    senses: { 'percezione cieca': '9 m', 'Percezione passiva': 11 },
    languages: '',
    cr: 1, xp: 200, proficiency_bonus: 2,
    traits: [
      { name: 'Canto Ipnotico', desc: 'All\'inizio di ogni suo turno, la spina cantante emette un canto melodioso. Ogni creatura che non sia una pianta e che si trovi entro 9 m da essa e possa sentirla deve superare un tiro di salvezza su Saggezza con CD 11 o restare Affascinata fino all\'inizio del turno successivo della spina. Una creatura affascinata in questo modo si avvicina alla spina seguendo il percorso più breve possibile.' },
      { name: 'Mimetismo', desc: 'La spina cantante ha l\'aspetto di un cespuglio di rovi in fiore. Una creatura deve superare una prova di Saggezza (Percezione) con CD 15 per accorgersi che si tratta di una creatura, a meno che la spina non si muova o attacchi.' },
    ],
    actions: [
      { name: 'Frustata di Spine', desc: 'Attacco con Arma da Mischia: +4 per colpire, raggio 3 m, un obiettivo. Colpito: 7 (2d4 + 2) danni perforanti, e l\'obiettivo è Trattenuto da viticci finché non supera una prova di Forza con CD 12 alla fine di uno dei suoi turni.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['foresta', 'palude'],
    image_url: null,
    description: 'Radicata e immobile, la spina cantante attira le sue vittime con un canto dolce e ipnotico prima di avvolgerle in un nido di viticci spinati. Le si trova spesso al centro di radure insolitamente silenziose, dove le ossa sbiancate degli sfortunati fertilizzano il terreno. Creatura di taglia Media, di tipo pianta, non allineata. Grado di Sfida 1.',
  },
  {
    id: 'hb-guardiano-dargilla',
    name: 'Guardiano d\'Argilla',
    size: 'Large',
    type: 'construct',
    subtype: null,
    alignment: 'non allineato',
    ac: 15,
    hp: 51,
    hit_dice: '6d10+18',
    speed: { camminare: '6 m' },
    str: 18, dex: 9, con: 16, intl: 3, wis: 10, cha: 1,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: [],
    damage_immunities: ['veleno', 'psichico'],
    condition_immunities: ['Affascinato', 'Spossatezza', 'Spaventato', 'Paralizzato', 'Avvelenato'],
    senses: { scurovisione: '18 m', 'Percezione passiva': 10 },
    languages: 'comprende le lingue del suo creatore ma non può parlare',
    cr: 3, xp: 700, proficiency_bonus: 2,
    traits: [
      { name: 'Corpo Indistruttibile', desc: 'Il guardiano è immune a qualsiasi malattia e non necessita di aria, cibo, acqua o sonno.' },
      { name: 'Programmato', desc: 'Il guardiano obbedisce fedelmente agli ordini impartitigli dal suo creatore al momento della sua animazione, interpretandoli alla lettera.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'Il guardiano esegue due attacchi con i pugni d\'argilla.' },
      { name: 'Pugno d\'Argilla', desc: 'Attacco con Arma da Mischia: +6 per colpire, raggio 1,5 m, un obiettivo. Colpito: 10 (2d6 + 3) danni contundenti.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['urbano', 'sotterraneo'],
    image_url: null,
    description: 'Plasmato da argilla rituale e cotto in forni incantati, il guardiano d\'argilla veglia silenzioso su templi e tesori, immobile per decenni finché non viene attivato da un intruso o da un comando del suo creatore. Creatura di taglia Grande, di tipo costrutto, non allineata. Grado di Sfida 3.',
  },
  {
    id: 'hb-strige-lunare',
    name: 'Strige Lunare',
    size: 'Medium',
    type: 'monstrosity',
    subtype: null,
    alignment: 'neutrale',
    ac: 15,
    hp: 90,
    hit_dice: '12d8+36',
    speed: { camminare: '3 m', volare: '18 m' },
    str: 14, dex: 18, con: 16, intl: 7, wis: 16, cha: 11,
    saving_throws: {},
    skills: { Percezione: 6, Furtività: 7 },
    damage_vulnerabilities: [],
    damage_resistances: ['radiante'],
    damage_immunities: [],
    condition_immunities: [],
    senses: { scurovisione: '36 m', 'Percezione passiva': 16 },
    languages: '',
    cr: 5, xp: 1800, proficiency_bonus: 3,
    traits: [
      { name: 'Volo Silenzioso', desc: 'La strige lunare ha vantaggio alle prove di Destrezza (Furtività) effettuate mentre vola.' },
      { name: 'Vista Lunare', desc: 'La strige lunare ignora gli effetti dell\'oscurità, anche magica, entro 36 m, e ci vede normalmente al chiaro di luna.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'La strige lunare esegue due attacchi: uno con gli artigli e uno con il becco.' },
      { name: 'Artigli', desc: 'Attacco con Arma da Mischia: +7 per colpire, raggio 1,5 m, un obiettivo. Colpito: 11 (2d6 + 4) danni taglienti.' },
      { name: 'Becco', desc: 'Attacco con Arma da Mischia: +7 per colpire, raggio 1,5 m, un obiettivo. Colpito: 8 (1d8 + 4) danni perforanti.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['montagna', 'foresta', 'planare'],
    image_url: null,
    description: 'Ibrido fra gufo e pipistrello con piume argentate che luccicano sotto la luna piena, la strige lunare è una cacciatrice silenziosa legata a marea ed eclissi. Le tradizioni druidiche la considerano un presagio: vederne una in volo annuncia un cambiamento imminente. Creatura di taglia Media, di tipo mostruosità, di allineamento neutrale. Grado di Sfida 5.',
  },
  {
    id: 'hb-ondina-dellabisso-nero',
    name: 'Ondina dell\'Abisso Nero',
    size: 'Large',
    type: 'elemental',
    subtype: null,
    alignment: 'neutrale malvagio',
    ac: 16,
    hp: 130,
    hit_dice: '15d10+45',
    speed: { camminare: '3 m', nuotare: '12 m' },
    str: 18, dex: 16, con: 17, intl: 8, wis: 14, cha: 12,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: ['acido', 'freddo', 'fulmine'],
    damage_immunities: ['veleno'],
    condition_immunities: ['Spossatezza', 'Prono', 'Avvelenato'],
    senses: { scurovisione: '18 m', 'Percezione passiva': 14 },
    languages: 'Acquatico, Primordiale',
    cr: 8, xp: 3900, proficiency_bonus: 3,
    traits: [
      { name: 'Corpo d\'Acqua', desc: 'L\'ondina può muoversi attraverso uno spazio largo almeno 2,5 cm senza doversi rimpicciolire.' },
      { name: 'Ombra negli Abissi', desc: 'L\'ondina ha vantaggio alle prove di Destrezza (Furtività) effettuate in acque scure o profonde.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'L\'ondina esegue due attacchi con gli schiaffi d\'acqua.' },
      { name: 'Schiaffo d\'Acqua', desc: 'Attacco con Arma da Mischia: +7 per colpire, raggio 3 m, un obiettivo. Colpito: 16 (2d10 + 5) danni contundenti. Se l\'obiettivo è una creatura di taglia Grande o inferiore, deve superare un tiro di salvezza su Forza con CD 15 o essere Afferrata (CD per liberarsi 15) e iniziare ad annegare se non può respirare sott\'acqua.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['acquatico', 'costiero', 'planare'],
    image_url: null,
    description: 'Condensata dalle correnti più fredde e remote del Piano Elementale dell\'Acqua, l\'ondina dell\'abisso nero ribolle di un\'oscurità liquida che assorbe la luce. Affonda le navi non per fame, ma per il piacere di vederle scomparire nel buio. Creatura di taglia Grande, di tipo elementale, di allineamento neutrale malvagio. Grado di Sfida 8.',
  },
  {
    id: 'hb-custode-delle-rovine-stellari',
    name: 'Custode delle Rovine Stellari',
    size: 'Huge',
    type: 'construct',
    subtype: null,
    alignment: 'legale neutrale',
    ac: 18,
    hp: 195,
    hit_dice: '15d12+90',
    speed: { camminare: '9 m' },
    str: 22, dex: 12, con: 20, intl: 10, wis: 15, cha: 9,
    saving_throws: { COS: 9, SAG: 6 },
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: ['contundenti, perforanti e taglienti da armi non magiche'],
    damage_immunities: ['psichico', 'radiante'],
    condition_immunities: ['Affascinato', 'Spossatezza', 'Spaventato', 'Paralizzato', 'Avvelenato', 'Prono'],
    senses: { scurovisione: '36 m', 'percezione tellurica': '9 m', 'Percezione passiva': 12 },
    languages: 'comprende il Celestiale e il Primordiale ma non può parlare',
    cr: 12, xp: 8400, proficiency_bonus: 4,
    traits: [
      { name: 'Resistenza alla Magia', desc: 'Il custode ha vantaggio ai tiri di salvezza contro incantesimi e altri effetti magici.' },
      { name: 'Nucleo di Stelle Cadute', desc: 'Il corpo del custode è forgiato da frammenti di una stella caduta e brilla debolmente di luce blu-bianca anche nell\'oscurità totale.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'Il custode esegue tre attacchi con il pugno siderale.' },
      { name: 'Pugno Siderale', desc: 'Attacco con Arma da Mischia: +12 per colpire, raggio 3 m, un obiettivo. Colpito: 19 (3d8 + 6) danni contundenti più 7 (2d6) danni radianti.' },
      { name: 'Raggio Stellare (Ricarica 5–6)', desc: 'Il custode emette un raggio di energia stellare lungo una linea di 18 m e larga 1,5 m. Ogni creatura in quell\'area deve effettuare un tiro di salvezza su Destrezza con CD 18, subendo 36 (8d8) danni radianti in caso di fallimento, o la metà dei danni in caso di successo.' },
    ],
    legendary_actions: [
      { name: 'Colpo Rapido', desc: 'Il custode esegue un attacco con il pugno siderale.' },
      { name: 'Passo Stellare', desc: 'Il custode si teletrasporta magicamente, insieme a qualsiasi equipaggiamento indossato o trasportato, in uno spazio libero che può vedere entro 9 m.' },
      { name: 'Onda Celeste (Costa 2 Azioni)', desc: 'Il custode rilascia un\'onda di energia stellare. Ogni creatura entro 4,5 m da esso deve superare un tiro di salvezza su Costituzione con CD 16 o essere Stordita fino alla fine del suo turno successivo.' },
    ],
    reactions: [],
    environments: ['sotterraneo', 'planare', 'montagna'],
    image_url: null,
    description: 'Eretto a guardia di rovine sepolte sotto un cratere meteoritico, il custode delle rovine stellari è un costrutto antico forgiato per proteggere un segreto che nemmeno il suo creatore osò scrivere. Si muove con lentezza solenne ma reagisce con la velocità della luce stellare a qualunque intrusione. Creatura di taglia Enorme, di tipo costrutto, di allineamento legale neutrale. Grado di Sfida 12.',
  },
  {
    id: 'hb-spettro-del-faro',
    name: 'Spettro del Faro',
    size: 'Medium',
    type: 'undead',
    subtype: null,
    alignment: 'neutrale malvagio',
    ac: 13,
    hp: 67,
    hit_dice: '9d8+27',
    speed: { camminare: '0 m', volare: '12 m (fluttuante)' },
    str: 6, dex: 16, con: 16, intl: 12, wis: 14, cha: 15,
    saving_throws: {},
    skills: { Percezione: 4 },
    damage_vulnerabilities: [],
    damage_resistances: ['acido', 'fulmine', 'contundenti, perforanti e taglienti da armi non magiche'],
    damage_immunities: ['freddo', 'necrotico', 'veleno'],
    condition_immunities: ['Affascinato', 'Spossatezza', 'Spaventato', 'Afferrato', 'Paralizzato', 'Pietrificato', 'Avvelenato', 'Prono', 'Trattenuto'],
    senses: { scurovisione: '18 m', 'Percezione passiva': 14 },
    languages: 'comprende le lingue che conosceva in vita ma non può parlare',
    cr: 4, xp: 1100, proficiency_bonus: 2,
    traits: [
      { name: 'Movimento Incorporeo', desc: 'Lo spettro può muoversi attraverso spazi occupati e oggetti solidi come se fossero terreno difficile. Subisce 5 (1d10) danni da forza se termina il suo turno dentro un oggetto.' },
      { name: 'Sensibilità al Faro', desc: 'Lo spettro è incapace di allontanarsi più di 18 m dal faro o dal relitto a cui è legato.' },
    ],
    actions: [
      { name: 'Tocco Logorante', desc: 'Attacco con Incantesimo a Distanza: +4 per colpire, raggio 1,5 m, un obiettivo. Colpito: 16 (3d10) danni necrotici, e il massimo dei punti ferita dell\'obiettivo si riduce di un ammontare pari ai danni subiti. La riduzione dura finché l\'obiettivo non completa un riposo lungo. L\'obiettivo muore se questo effetto riduce il suo massimo dei punti ferita a 0.' },
      { name: 'Bagliore Ingannevole (Ricarica 5–6)', desc: 'Lo spettro proietta una falsa luce di faro. Ogni creatura entro 18 m che possa vederla deve superare un tiro di salvezza su Saggezza con CD 13 o essere Affascinata per 1 minuto, muovendosi verso la luce lungo il percorso più diretto, anche se ciò significa attraversare terreno pericoloso. Una creatura affascinata in questo modo ripete il tiro di salvezza alla fine di ogni suo turno, terminando l\'effetto su di sé con un successo.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['costiero', 'planare'],
    image_url: null,
    description: 'Legato per sempre al faro che non riuscì a salvare, lo spettro del faro riaccende notte dopo notte una luce fantasma per attirare le navi verso gli scogli, rivivendo all\'infinito il naufragio che lo uccise. Creatura di taglia Media, non morta, di allineamento neutrale malvagio. Grado di Sfida 4.',
  },
  {
    id: 'hb-diavoletto-dei-contratti',
    name: 'Diavoletto dei Contratti',
    size: 'Tiny',
    type: 'fiend',
    subtype: 'diavolo',
    alignment: 'legale malvagio',
    ac: 13,
    hp: 21,
    hit_dice: '6d4+6',
    speed: { camminare: '3 m', volare: '9 m' },
    str: 6, dex: 17, con: 13, intl: 14, wis: 12, cha: 16,
    saving_throws: {},
    skills: { Inganno: 5, Persuasione: 5 },
    damage_vulnerabilities: [],
    damage_resistances: ['freddo', 'fuoco', 'fulmine', "contundenti, perforanti e taglienti da armi non magiche e non d'argento"],
    damage_immunities: ['veleno'],
    condition_immunities: ['Avvelenato'],
    senses: { scurovisione: '36 m', 'Percezione passiva': 11 },
    languages: 'Infernale, Comune, telepatia 36 m',
    cr: 2, xp: 450, proficiency_bonus: 2,
    traits: [
      { name: 'Mutaforma', desc: 'Il diavoletto può usare un\'azione per assumere l\'aspetto di una bestiola Minuscola, come un ratto, un corvo o un gatto nero, o di nuovo il suo vero aspetto. Le sue statistiche restano le stesse in ogni forma, eccetto la velocità di volo, disponibile solo in forme che la possiedono naturalmente. Qualunque equipaggiamento indossato o trasportato non viene trasformato.' },
    ],
    actions: [
      { name: 'Morso', desc: 'Attacco con Arma da Mischia: +5 per colpire, raggio 1,5 m, un obiettivo. Colpito: 5 (1d4 + 3) danni perforanti.' },
      { name: 'Inchiostro Vincolante (Ricarica 5–6)', desc: 'Il diavoletto bersaglia una creatura che riesce a vedere entro 9 m e le offre un contratto infernale invisibile. L\'obiettivo deve superare un tiro di salvezza su Carisma con CD 13 o essere magicamente vincolato a rispettare la lettera della prima promessa verbale che fa nei successivi 10 minuti; infrangerla inflige all\'obiettivo 18 (4d8) danni psichici e lo rende Spaventato dal diavoletto per 1 minuto.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['planare', 'urbano'],
    image_url: null,
    description: 'Inviato dai gradi più bassi delle legioni infernali per concludere affari sussurrati nei vicoli e nelle taverne, il diavoletto dei contratti colleziona promesse spezzate come trofei. Cambia forma con disinvoltura per intrufolarsi ovunque ci sia un\'anima disposta a negoziare. Creatura di taglia Minuscola, di tipo demone, di allineamento legale malvagio. Grado di Sfida 2.',
  },
  {
    id: 'hb-serpe-di-vetro',
    name: 'Serpe di Vetro',
    size: 'Small',
    type: 'dragon',
    subtype: null,
    alignment: 'neutrale',
    ac: 17,
    hp: 85,
    hit_dice: '13d6+39',
    speed: { camminare: '9 m', scavare: '3 m' },
    str: 16, dex: 16, con: 16, intl: 8, wis: 13, cha: 10,
    saving_throws: {},
    skills: { Percezione: 4 },
    damage_vulnerabilities: ['tuono'],
    damage_resistances: ['perforanti e taglienti da armi non magiche'],
    damage_immunities: [],
    condition_immunities: [],
    senses: { scurovisione: '18 m', 'percezione cieca': '4,5 m', 'Percezione passiva': 14 },
    languages: 'Draconico',
    cr: 6, xp: 2300, proficiency_bonus: 3,
    traits: [
      { name: 'Corpo di Vetro Vivente', desc: 'Il corpo cristallino della serpe la rende fragile contro le vibrazioni: ha vulnerabilità ai danni da tuono, ma resistenza ai danni perforanti e taglienti delle armi non magiche.' },
      { name: 'Riflessi Accecanti', desc: 'Quando la serpe è colpita dalla luce solare diretta, ogni creatura entro 3 m da essa che possa vederla deve superare un tiro di salvezza su Costituzione con CD 13 o essere Accecata per 1 minuto.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'La serpe esegue due attacchi: uno con il morso e uno con la coda.' },
      { name: 'Morso', desc: 'Attacco con Arma da Mischia: +6 per colpire, raggio 3 m, un obiettivo. Colpito: 13 (2d8 + 3) danni perforanti.' },
      { name: 'Coda', desc: 'Attacco con Arma da Mischia: +6 per colpire, raggio 4,5 m, un obiettivo. Colpito: 10 (2d6 + 3) danni contundenti.' },
      { name: 'Spruzzo di Schegge (Ricarica 5–6)', desc: 'La serpe espelle una nube di schegge di vetro in un cono di 9 m. Ogni creatura in quell\'area deve effettuare un tiro di salvezza su Destrezza con CD 14, subendo 27 (6d8) danni taglienti in caso di fallimento, o la metà dei danni in caso di successo.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['deserto', 'sotterraneo', 'montagna'],
    image_url: null,
    description: 'Affine ai draghi minori ma fatta di un cristallo trasparente che canta al vento, la serpe di vetro si annida tra geodi e caverne di sale, mimetizzandosi come stalattiti scintillanti finché la preda non è abbastanza vicina. Creatura di taglia Piccola, di tipo drago, di allineamento neutrale. Grado di Sfida 6.',
  },
  {
    id: 'hb-colosso-di-radici',
    name: 'Colosso di Radici',
    size: 'Huge',
    type: 'giant',
    subtype: null,
    alignment: 'neutrale',
    ac: 16,
    hp: 115,
    hit_dice: '10d12+50',
    speed: { camminare: '9 m' },
    str: 22, dex: 8, con: 20, intl: 6, wis: 12, cha: 7,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: ['fuoco'],
    damage_resistances: ['perforanti'],
    damage_immunities: ['veleno'],
    condition_immunities: ['Avvelenato', 'Affascinato'],
    senses: { 'Percezione passiva': 11 },
    languages: 'Gigante, Silvano',
    cr: 7, xp: 2900, proficiency_bonus: 3,
    traits: [
      { name: 'Rigenerazione Boschiva', desc: 'Se si trova in un\'area di terreno selvaggio o foresta, il colosso recupera 10 punti ferita all\'inizio del suo turno se ha almeno 1 punto ferita.' },
      { name: 'Radici Aggrappanti', desc: 'Il terreno entro 3 m dal colosso è terreno difficile per le sue creature ostili, a causa delle radici che si protendono dal suo corpo.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'Il colosso esegue due attacchi con il pugno di corteccia.' },
      { name: 'Pugno di Corteccia', desc: 'Attacco con Arma da Mischia: +9 per colpire, raggio 3 m, un obiettivo. Colpito: 18 (2d10 + 6) danni contundenti.' },
      { name: 'Scossa Tellurica (Ricarica 5–6)', desc: 'Il colosso colpisce il terreno. Ogni creatura entro 4,5 m da lui, eccetto lui stesso, deve superare un tiro di salvezza su Destrezza con CD 16 o subire 14 (4d6) danni contundenti ed essere Prona.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['foresta', 'collina'],
    image_url: null,
    description: 'Nato quando la radice di un albero millenario si è risvegliata dopo un fulmine, il colosso di radici cammina lentamente attraverso le foreste antiche, sradicando chiunque osi disboscarle. Creatura di taglia Enorme, di tipo gigante, di allineamento neutrale. Grado di Sfida 7.',
  },
  {
    id: 'hb-cantastorie-di-bruma',
    name: 'Cantastorie di Bruma',
    size: 'Medium',
    type: 'fey',
    subtype: null,
    alignment: 'caotico neutrale',
    ac: 14,
    hp: 49,
    hit_dice: '11d8',
    speed: { camminare: '9 m', volare: '6 m (solo in forma di nebbia)' },
    str: 10, dex: 16, con: 11, intl: 13, wis: 14, cha: 18,
    saving_throws: {},
    skills: { Intrattenere: 6, Persuasione: 6, Inganno: 6 },
    damage_vulnerabilities: [],
    damage_resistances: [],
    damage_immunities: [],
    condition_immunities: [],
    senses: { scurovisione: '18 m', 'Percezione passiva': 12 },
    languages: 'Silvano, Comune',
    cr: 3, xp: 700, proficiency_bonus: 2,
    traits: [
      { name: 'Forma di Nebbia', desc: 'Il cantastorie può usare un\'azione bonus per trasformarsi in una nube di nebbia sottile, o per tornare alla sua forma vera. Mentre è nebbia, è immune ai danni contundenti, perforanti e taglienti, ha velocità di volo 6 m, può fluttuare attraverso spazi larghi almeno 2,5 cm senza spremersi, e non può attaccare né lanciare incantesimi.' },
      { name: 'Eco Incantata', desc: 'Il cantastorie ha vantaggio alle prove di Carisma (Intrattenere e Persuasione) effettuate verso creature che riescono a sentirlo cantare.' },
    ],
    actions: [
      { name: 'Pugnale Spettrale', desc: 'Attacco con Arma da Mischia o a Distanza: +5 per colpire, raggio 1,5 m o gittata 6/18 m, un obiettivo. Colpito: 6 (1d4 + 4) danni perforanti.' },
      { name: 'Melodia Disorientante (Ricarica 5–6)', desc: 'Ogni creatura entro 9 m dal cantastorie che possa sentirlo deve superare un tiro di salvezza su Saggezza con CD 14 o essere Confusa per 1 minuto, ripetendo il tiro di salvezza alla fine di ogni suo turno con un successo che termina l\'effetto su di sé.' },
    ],
    legendary_actions: [],
    reactions: [
      { name: 'Passo nella Bruma', desc: 'Quando subisce danni da un attacco in mischia, il cantastorie può trasformarsi in nebbia e teletrasportarsi in uno spazio libero che può vedere entro 6 m, riapparendo nella sua forma normale.' },
    ],
    environments: ['foresta', 'planare'],
    image_url: null,
    description: 'Spirito di un menestrello morto a metà di una canzone, il cantastorie di bruma riappare nelle notti di nebbia per terminare racconti mai conclusi, intrappolando chi si ferma ad ascoltare in melodie che confondono il tempo. Creatura di taglia Media, fata, di allineamento caotico neutrale. Grado di Sfida 3.',
  },
  {
    id: 'hb-melma-dell-eco',
    name: "Melma dell'Eco",
    size: 'Large',
    type: 'ooze',
    subtype: null,
    alignment: 'non allineato',
    ac: 8,
    hp: 93,
    hit_dice: '11d10+33',
    speed: { camminare: '3 m' },
    str: 16, dex: 2, con: 16, intl: 1, wis: 6, cha: 1,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: ['acido'],
    damage_immunities: [],
    condition_immunities: ['Cieco', 'Spossatezza', 'Prono'],
    senses: { 'percezione cieca': '18 m (cieco oltre questo raggio)', 'Percezione passiva': 8 },
    languages: '',
    cr: 5, xp: 1800, proficiency_bonus: 3,
    traits: [
      { name: 'Eco Vivente', desc: 'Quando la melma subisce danni da tuono, si divide in due melme identiche se ha almeno 10 punti ferita dopo i danni; ciascuna nuova melma ha punti ferita pari alla metà di quelli rimasti alla melma originale (arrotondati per difetto). Le nuove melme sono creature separate.' },
      { name: 'Corpo Amorfo', desc: 'La melma può muoversi attraverso uno spazio largo almeno 2,5 cm senza doversi rimpicciolire.' },
    ],
    actions: [
      { name: 'Pseudopodo', desc: 'Attacco con Arma da Mischia: +6 per colpire, raggio 1,5 m, un obiettivo. Colpito: 14 (2d10 + 3) danni contundenti più 4 (1d8) danni da acido.' },
      { name: 'Urlo Riecheggiante (Ricarica 5–6)', desc: 'La melma emette un urlo distorto. Ogni creatura entro 6 m da essa deve superare un tiro di salvezza su Costituzione con CD 14, subendo 18 (4d8) danni da tuono ed essendo Assordata per 1 minuto in caso di fallimento, o subendo solo la metà dei danni e senza essere assordata in caso di successo.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['sotterraneo', 'urbano'],
    image_url: null,
    description: 'Densa e silenziosa finché qualcosa non la disturba, la melma dell\'eco ripete ogni suono che assorbe distorcendolo in urla innaturali, e si moltiplica violentemente quando lo stesso rumore la scuote con sufficiente forza. Creatura di taglia Grande, melma, non allineata. Grado di Sfida 5.',
  },
];

export const HOMEBREW_ITEMS = [
  {
    id: 'hb-item-fibbia-del-passo-silenzioso',
    name: 'Fibbia del Passo Silenzioso',
    category: 'Wondrous Items',
    rarity: 'common',
    attunement: 0,
    weight: 0.1,
    description: 'Oggetto meraviglioso, comune\n\nQuesta piccola fibbia in peltro, lavorata a forma di impronta felina, può essere fissata a una cintura, uno stivale o un mantello. Finché la indossi, hai vantaggio alle prove di Destrezza (Furtività) effettuate per muoverti silenziosamente, a condizione che tu non indossi armatura media o pesante.',
  },
  {
    id: 'hb-item-lente-dellindovino',
    name: 'Lente dell\'Indovino',
    category: 'Wondrous Items',
    rarity: 'uncommon',
    attunement: 1,
    weight: 0.1,
    description: 'Oggetto meraviglioso, non comune (richiede sintonia)\n\nQuesta lente monocolo dalla montatura di rame è incisa con minuscole rune divinatorie. Mentre la indossi, hai vantaggio alle prove di Intelligenza (Indagare) effettuate per individuare proprietà magiche di un oggetto o di un luogo. Una volta al giorno puoi guardare attraverso la lente e lanciare l\'incantesimo individuazione del magico senza spendere una spazio incantesimo né componenti.',
  },
  {
    id: 'hb-item-bracciale-di-marea-ferma',
    name: 'Bracciale di Marea Ferma',
    category: 'Wondrous Items',
    rarity: 'rare',
    attunement: 1,
    weight: 0.5,
    description: 'Oggetto meraviglioso, raro (richiede sintonia)\n\nIntagliato da un singolo pezzo di corallo pietrificato e legato con fili d\'argento, questo bracciale pulsa debolmente al contatto con l\'acqua salata. Mentre lo indossi, hai resistenza ai danni da freddo, puoi respirare sott\'acqua e la tua velocità di nuoto è pari alla tua velocità sul terreno. Inoltre, mentre sei immerso in acqua, hai vantaggio ai tiri di salvezza contro essere spinto, afferrato o trattenuto da correnti o creature acquatiche.',
  },
  {
    id: 'hb-item-tomo-delle-pagine-vuote',
    name: 'Tomo delle Pagine Vuote',
    category: 'Wondrous Items',
    rarity: 'very_rare',
    attunement: 1,
    weight: 3,
    description: 'Oggetto meraviglioso, molto raro (richiede sintonia da parte di un lanciatore di incantesimi)\n\nLe pagine di questo tomo rilegato in pelle scura appaiono completamente bianche finché non vi imprigioni un incantesimo. Quando ti sintonizzi con il tomo, puoi scegliere un incantesimo che conosci o hai preparato, di livello 5 o inferiore, e "scriverlo" nelle pagine spendendo uno spazio incantesimo del livello appropriato; l\'incantesimo appare come testo dorato luminescente. In seguito, puoi usare un\'azione per lanciare l\'incantesimo imprigionato dal tomo senza spendere uno spazio incantesimo né componenti materiali (a meno che non si consumino), usando il tuo modificatore di lancio incantesimi. Una volta lanciato in questo modo, le pagine tornano bianche e il tomo non può essere usato di nuovo finché non trascorre un\'alba.',
  },
  {
    id: 'hb-item-corona-dei-tre-inverni',
    name: 'Corona dei Tre Inverni',
    category: 'Wondrous Items',
    rarity: 'legendary',
    attunement: 1,
    weight: 1,
    description: 'Oggetto meraviglioso, leggendario (richiede sintonia)\n\nForgiata per un sovrano che regnò su tre inverni consecutivi senza concedere mai un\'alba di disgelo, questa corona di ferro brinato non si scalda mai al tocco. Mentre la indossi, hai resistenza ai danni da freddo e sei immune agli effetti ambientali del freddo estremo. Una volta per giorno puoi usare un\'azione per far emanare dalla corona un cono di gelo lungo 9 m: ogni creatura in quell\'area deve superare un tiro di salvezza su Costituzione con CD 16, subendo 45 (10d8) danni da freddo in caso di fallimento, o la metà dei danni in caso di successo.\n\n***Maledizione.*** La corona porta in sé l\'orgoglio gelido del suo primo sovrano. Mentre la indossi, hai svantaggio alle prove di Carisma che richiedano empatia, calore o compassione genuina, e i tuoi sogni sono visitati da inverni che non hai mai vissuto.',
  },
  {
    id: 'hb-item-cuore-del-crogiolo-primordiale',
    name: 'Cuore del Crogiolo Primordiale',
    category: 'Wondrous Items',
    rarity: 'artifact',
    attunement: 1,
    weight: 2,
    description: 'Oggetto meraviglioso, artefatto (richiede sintonia)\n\nQuesto cristallo a forma di cuore, caldo come brace viva, è ciò che resta del nucleo di un elementale del fuoco primordiale annientato all\'alba dei tempi. Pulsa lentamente come un battito cardiaco e illumina di luce arancione qualunque stanza buia.\n\nMentre sei sintonizzato con il cuore, sei immune ai danni da fuoco e i tuoi incantesimi che infliggono danni da fuoco infliggono 1d6 danni da fuoco aggiuntivi. Una volta per giorno puoi usare un\'azione per far detonare il cuore in una nova di fiamme: ogni creatura entro 6 m da te, escluso te stesso, deve superare un tiro di salvezza su Destrezza con CD 18, subendo 66 (12d10) danni da fuoco in caso di fallimento, o la metà dei danni in caso di successo.\n\n***Difetto Primordiale.*** Il cuore contiene ancora una scintilla della furia dell\'elementale distrutto. Ogni volta che termini un riposo lungo mentre sei sintonizzato con il cuore, tira un d20: con un risultato di 1, il cuore detona spontaneamente, infliggendo l\'effetto della nova di fiamme centrata su di te, calcolando il tiro di salvezza con CD 18 per ogni altra creatura nel raggio.\n\n***Distruzione.*** Il cuore del crogiolo primordiale può essere distrutto solo gettandolo nel cuore di un vulcano attivo durante un\'eruzione, mentre chi lo getta rinuncia ad alta voce a ogni pretesa di potere sul fuoco. In quel momento il cuore si dissolve in cenere e l\'eruzione si placa innaturalmente in pochi istanti.',
  },
  {
    id: 'hb-item-spada-del-crepuscolo-quieto',
    name: 'Spada del Crepuscolo Quieto',
    category: 'Weapon',
    rarity: 'rare',
    attunement: 1,
    weight: 1.5,
    description: 'Arma (qualsiasi spada), rara (richiede sintonia)\n\nLa lama di quest\'arma è forgiata in un acciaio blu-violaceo che assorbe la luce diurna e la restituisce come un tenue bagliore crepuscolare. Ottieni un bonus di +1 ai tiri per colpire e ai tiri di danno effettuati con questa arma magica.\n\nUna volta per riposo breve o lungo, puoi usare un\'azione bonus per far calare un silenzio innaturale: per 1 minuto, tu e ogni creatura di tua scelta entro 3 m da te avete vantaggio alle prove di Destrezza (Furtività), e gli attacchi che effettuate con questa spada non emettono alcun suono.',
  },
  {
    id: 'hb-item-corazza-di-scaglie-spente',
    name: 'Corazza di Scaglie Spente',
    category: 'Armor',
    rarity: 'uncommon',
    attunement: 0,
    weight: 18,
    description: 'Armatura (media), non comune\n\nTemprata con cenere vulcanica e scaglie di una creatura ormai estinta, questa corazza grigio-opaca assorbe il calore invece di rifletterlo. Mentre la indossi, hai resistenza ai danni da fuoco e il bonus al tiro per colpire degli attacchi infuocati contro di te non supera mai +5, indipendentemente dal bonus reale dell\'attaccante.',
  },
  {
    id: 'hb-item-filtro-di-passo-felpato',
    name: 'Filtro di Passo Felpato',
    category: 'Potion',
    rarity: 'common',
    attunement: 0,
    weight: 0.5,
    description: 'Pozione, comune\n\nQuesto liquido grigio perla è denso come miele e non produce alcun rumore quando viene versato. Per 1 ora dopo averlo bevuto, i tuoi passi non producono alcun suono, indipendentemente dalla superficie su cui cammini, e hai vantaggio alla prima prova di Destrezza (Furtività) che effettui in quel periodo.',
  },
  {
    id: 'hb-item-anello-delle-maree-lontane',
    name: 'Anello delle Maree Lontane',
    category: 'Ring',
    rarity: 'very_rare',
    attunement: 1,
    weight: 0,
    description: 'Anello, molto raro (richiede sintonia)\n\nIncastonato con una perla grigio-azzurra che sembra muoversi come acqua se osservata da vicino, questo anello pulsa debolmente seguendo un ritmo di marea che non corrisponde a nessuna costa vicina. Mentre lo indossi, puoi respirare normalmente sott\'acqua e la profondità dell\'acqua non ha alcun effetto sulla pressione che subisci.\n\nL\'anello ha 3 cariche. Mentre lo indossi, puoi usare un\'azione e spendere 1 carica per lanciare controllo dell\'acqua (CD per il tiro di salvezza 17) oppure onda tonante (CD 17). L\'anello recupera 1d3 cariche spese ogni giorno all\'alba.',
  },
  {
    id: 'hb-item-bastone-del-bosco-sussurrante',
    name: 'Bastone del Bosco Sussurrante',
    category: 'Staff',
    rarity: 'rare',
    attunement: 1,
    weight: 4,
    description: 'Bastone, raro (richiede sintonia da parte di un druido o ranger)\n\nIntagliato da un singolo ramo di quercia ancora vivo, questo bastone germoglia foglie fresche a ogni luna piena, indipendentemente dalla stagione. Mentre lo impugni, hai un bonus di +1 ai tiri per colpire e ai tiri di danno degli incantesimi.\n\nIl bastone ha 10 cariche e ne recupera 1d6+4 ogni giorno all\'alba. Mentre lo impugni, puoi spendere le cariche per lanciare uno dei seguenti incantesimi usando il tuo CD per i tiri di salvezza: parlare con gli animali (1 carica), trappola di spine (2 cariche), muro di spine (6 cariche). Puoi anche spendere 1 carica come azione per far germogliare radici dal terreno entro 18 m: una creatura a tua scelta in quell\'area deve superare un tiro di salvezza su Destrezza o avere la velocità ridotta a 0 fino alla fine del suo turno successivo.\n\nSe spendi l\'ultima carica del bastone, tira un d20. Con un risultato di 1, il bastone si secca e perde ogni proprietà magica.',
  },
  {
    id: 'hb-item-bacchetta-delle-scintille-pigre',
    name: 'Bacchetta delle Scintille Pigre',
    category: 'Wand',
    rarity: 'uncommon',
    attunement: 1,
    weight: 1,
    description: 'Bacchetta, non comune (richiede sintonia)\n\nQuesta sottile bacchetta di rame produce scintille dorate che cadono pigramente come foglie d\'autunno invece di scoccare in linea retta. Ha 6 cariche e ne recupera 1d6 ogni giorno all\'alba.\n\nMentre la tieni in mano, puoi usare un\'azione e spendere 1 carica per lanciare uno dei seguenti incantesimi (CD per il tiro di salvezza 13): proiettile di fuoco (1 carica), luce danzante (gratuito, senza spendere cariche), oppure raggio di fuoco come incantesimo di livello 2 (2 cariche). Se spendi l\'ultima carica, tira un d20: con un risultato di 1, la bacchetta si dissolve in cenere fredda e viene distrutta.',
  },
];
