// Original homebrew creatures and magic items, authored from scratch for
// this project (not derived from or copying any published statblock/item).
// Added to broaden the bestiary/compendio beyond the translated SRD content,
// per the project's "SRD tradotta + homebrew originale" sourcing decision
// (no scraping of copyrighted third-party compendia). Stable, human-readable
// ids so re-seeding is idempotent.

export const HOMEBREW_CREATURES = [
  {
    id: 'hb-sciacallo-di-brace',
    name: 'Sciacallo di Brace',
    size: 'Small',
    type: 'beast',
    subtype: null,
    alignment: 'non allineato',
    ac: 13,
    hp: 7,
    hit_dice: '2d6',
    speed: { camminare: '12 m' },
    str: 8, dex: 15, con: 11, intl: 3, wis: 12, cha: 6,
    saving_throws: {},
    skills: { Percezione: 3 },
    damage_vulnerabilities: [],
    damage_resistances: [],
    damage_immunities: ['fuoco'],
    condition_immunities: [],
    senses: { scurovisione: '18 m', 'Percezione passiva': 13 },
    languages: '',
    cr: 0.125, xp: 25, proficiency_bonus: 2,
    traits: [
      { name: 'Fiuto Acuto', desc: 'Lo sciacallo ha vantaggio alle prove di Saggezza (Percezione) che si basano sull\'olfatto.' },
      { name: 'Pelle Incandescente', desc: 'Una creatura che colpisce lo sciacallo con un attacco in mischia mentre non indossa guanti o protezioni adeguate subisce 1 danno da fuoco.' },
    ],
    actions: [
      { name: 'Morso', desc: 'Attacco con Arma da Mischia: +4 per colpire, raggio 1,5 m, un obiettivo. Colpito: 4 (1d4 + 2) danni perforanti più 1 (1d4) danni da fuoco.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['deserto', 'collina'],
    image_url: null,
    description: 'Lo sciacallo di brace è un predatore delle terre aride il cui mantello arso scintilla come carbone ardente. Caccia in piccoli branchi notturni, attratto dal calore dei fuochi da campo, e la sua pelle resta calda al tatto molto tempo dopo la sua morte. Creatura di taglia Piccola, di tipo bestia, non allineata. Grado di Sfida 1/8.',
  },
  {
    id: 'hb-spina-cantante',
    name: 'Spina Cantante',
    size: 'Medium',
    type: 'plant',
    subtype: null,
    alignment: 'non allineato',
    ac: 12,
    hp: 22,
    hit_dice: '4d8+4',
    speed: { camminare: '3 m' },
    str: 14, dex: 8, con: 14, intl: 4, wis: 13, cha: 11,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: ['fuoco'],
    damage_resistances: [],
    damage_immunities: [],
    condition_immunities: [],
    senses: { 'percezione cieca': '9 m', 'Percezione passiva': 11 },
    languages: '',
    cr: 1, xp: 200, proficiency_bonus: 2,
    traits: [
      { name: 'Canto Ipnotico', desc: 'All\'inizio di ogni suo turno, la spina cantante emette un canto melodioso. Ogni creatura che non sia una pianta e che si trovi entro 9 m da essa e possa sentirla deve superare un tiro di salvezza su Saggezza con CD 11 o restare Affascinata fino all\'inizio del turno successivo della spina. Una creatura affascinata in questo modo si avvicina alla spina seguendo il percorso più breve possibile.' },
      { name: 'Mimetismo', desc: 'La spina cantante ha l\'aspetto di un cespuglio di rovi in fiore. Una creatura deve superare una prova di Saggezza (Percezione) con CD 15 per accorgersi che si tratta di una creatura, a meno che la spina non si muova o attacchi.' },
    ],
    actions: [
      { name: 'Frustata di Spine', desc: 'Attacco con Arma da Mischia: +4 per colpire, raggio 3 m, un obiettivo. Colpito: 7 (2d4 + 2) danni perforanti, e l\'obiettivo è Trattenuto da viticci finché non supera una prova di Forza con CD 12 alla fine di uno dei suoi turni.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['foresta', 'palude'],
    image_url: null,
    description: 'Radicata e immobile, la spina cantante attira le sue vittime con un canto dolce e ipnotico prima di avvolgerle in un nido di viticci spinati. Le si trova spesso al centro di radure insolitamente silenziose, dove le ossa sbiancate degli sfortunati fertilizzano il terreno. Creatura di taglia Media, di tipo pianta, non allineata. Grado di Sfida 1.',
  },
  {
    id: 'hb-guardiano-dargilla',
    name: 'Guardiano d\'Argilla',
    size: 'Large',
    type: 'construct',
    subtype: null,
    alignment: 'non allineato',
    ac: 15,
    hp: 51,
    hit_dice: '6d10+18',
    speed: { camminare: '6 m' },
    str: 18, dex: 9, con: 16, intl: 3, wis: 10, cha: 1,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: [],
    damage_immunities: ['veleno', 'psichico'],
    condition_immunities: ['Affascinato', 'Spossatezza', 'Spaventato', 'Paralizzato', 'Avvelenato'],
    senses: { scurovisione: '18 m', 'Percezione passiva': 10 },
    languages: 'comprende le lingue del suo creatore ma non può parlare',
    cr: 3, xp: 700, proficiency_bonus: 2,
    traits: [
      { name: 'Corpo Indistruttibile', desc: 'Il guardiano è immune a qualsiasi malattia e non necessita di aria, cibo, acqua o sonno.' },
      { name: 'Programmato', desc: 'Il guardiano obbedisce fedelmente agli ordini impartitigli dal suo creatore al momento della sua animazione, interpretandoli alla lettera.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'Il guardiano esegue due attacchi con i pugni d\'argilla.' },
      { name: 'Pugno d\'Argilla', desc: 'Attacco con Arma da Mischia: +6 per colpire, raggio 1,5 m, un obiettivo. Colpito: 10 (2d6 + 3) danni contundenti.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['urbano', 'sotterraneo'],
    image_url: null,
    description: 'Plasmato da argilla rituale e cotto in forni incantati, il guardiano d\'argilla veglia silenzioso su templi e tesori, immobile per decenni finché non viene attivato da un intruso o da un comando del suo creatore. Creatura di taglia Grande, di tipo costrutto, non allineata. Grado di Sfida 3.',
  },
  {
    id: 'hb-strige-lunare',
    name: 'Strige Lunare',
    size: 'Medium',
    type: 'monstrosity',
    subtype: null,
    alignment: 'neutrale',
    ac: 15,
    hp: 90,
    hit_dice: '12d8+36',
    speed: { camminare: '3 m', volare: '18 m' },
    str: 14, dex: 18, con: 16, intl: 7, wis: 16, cha: 11,
    saving_throws: {},
    skills: { Percezione: 6, Furtività: 7 },
    damage_vulnerabilities: [],
    damage_resistances: ['radiante'],
    damage_immunities: [],
    condition_immunities: [],
    senses: { scurovisione: '36 m', 'Percezione passiva': 16 },
    languages: '',
    cr: 5, xp: 1800, proficiency_bonus: 3,
    traits: [
      { name: 'Volo Silenzioso', desc: 'La strige lunare ha vantaggio alle prove di Destrezza (Furtività) effettuate mentre vola.' },
      { name: 'Vista Lunare', desc: 'La strige lunare ignora gli effetti dell\'oscurità, anche magica, entro 36 m, e ci vede normalmente al chiaro di luna.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'La strige lunare esegue due attacchi: uno con gli artigli e uno con il becco.' },
      { name: 'Artigli', desc: 'Attacco con Arma da Mischia: +7 per colpire, raggio 1,5 m, un obiettivo. Colpito: 11 (2d6 + 4) danni taglienti.' },
      { name: 'Becco', desc: 'Attacco con Arma da Mischia: +7 per colpire, raggio 1,5 m, un obiettivo. Colpito: 8 (1d8 + 4) danni perforanti.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['montagna', 'foresta', 'planare'],
    image_url: null,
    description: 'Ibrido fra gufo e pipistrello con piume argentate che luccicano sotto la luna piena, la strige lunare è una cacciatrice silenziosa legata a marea ed eclissi. Le tradizioni druidiche la considerano un presagio: vederne una in volo annuncia un cambiamento imminente. Creatura di taglia Media, di tipo mostruosità, di allineamento neutrale. Grado di Sfida 5.',
  },
  {
    id: 'hb-ondina-dellabisso-nero',
    name: 'Ondina dell\'Abisso Nero',
    size: 'Large',
    type: 'elemental',
    subtype: null,
    alignment: 'neutrale malvagio',
    ac: 16,
    hp: 130,
    hit_dice: '15d10+45',
    speed: { camminare: '3 m', nuotare: '12 m' },
    str: 18, dex: 16, con: 17, intl: 8, wis: 14, cha: 12,
    saving_throws: {},
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: ['acido', 'freddo', 'fulmine'],
    damage_immunities: ['veleno'],
    condition_immunities: ['Spossatezza', 'Prono', 'Avvelenato'],
    senses: { scurovisione: '18 m', 'Percezione passiva': 14 },
    languages: 'Acquatico, Primordiale',
    cr: 8, xp: 3900, proficiency_bonus: 3,
    traits: [
      { name: 'Corpo d\'Acqua', desc: 'L\'ondina può muoversi attraverso uno spazio largo almeno 2,5 cm senza doversi rimpicciolire.' },
      { name: 'Ombra negli Abissi', desc: 'L\'ondina ha vantaggio alle prove di Destrezza (Furtività) effettuate in acque scure o profonde.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'L\'ondina esegue due attacchi con gli schiaffi d\'acqua.' },
      { name: 'Schiaffo d\'Acqua', desc: 'Attacco con Arma da Mischia: +7 per colpire, raggio 3 m, un obiettivo. Colpito: 16 (2d10 + 5) danni contundenti. Se l\'obiettivo è una creatura di taglia Grande o inferiore, deve superare un tiro di salvezza su Forza con CD 15 o essere Afferrata (CD per liberarsi 15) e iniziare ad annegare se non può respirare sott\'acqua.' },
    ],
    legendary_actions: [],
    reactions: [],
    environments: ['acquatico', 'costiero', 'planare'],
    image_url: null,
    description: 'Condensata dalle correnti più fredde e remote del Piano Elementale dell\'Acqua, l\'ondina dell\'abisso nero ribolle di un\'oscurità liquida che assorbe la luce. Affonda le navi non per fame, ma per il piacere di vederle scomparire nel buio. Creatura di taglia Grande, di tipo elementale, di allineamento neutrale malvagio. Grado di Sfida 8.',
  },
  {
    id: 'hb-custode-delle-rovine-stellari',
    name: 'Custode delle Rovine Stellari',
    size: 'Huge',
    type: 'construct',
    subtype: null,
    alignment: 'legale neutrale',
    ac: 18,
    hp: 195,
    hit_dice: '15d12+90',
    speed: { camminare: '9 m' },
    str: 22, dex: 12, con: 20, intl: 10, wis: 15, cha: 9,
    saving_throws: { COS: 9, SAG: 6 },
    skills: {},
    damage_vulnerabilities: [],
    damage_resistances: ['contundenti, perforanti e taglienti da armi non magiche'],
    damage_immunities: ['psichico', 'radiante'],
    condition_immunities: ['Affascinato', 'Spossatezza', 'Spaventato', 'Paralizzato', 'Avvelenato', 'Prono'],
    senses: { scurovisione: '36 m', 'percezione tellurica': '9 m', 'Percezione passiva': 12 },
    languages: 'comprende il Celestiale e il Primordiale ma non può parlare',
    cr: 12, xp: 8400, proficiency_bonus: 4,
    traits: [
      { name: 'Resistenza alla Magia', desc: 'Il custode ha vantaggio ai tiri di salvezza contro incantesimi e altri effetti magici.' },
      { name: 'Nucleo di Stelle Cadute', desc: 'Il corpo del custode è forgiato da frammenti di una stella caduta e brilla debolmente di luce blu-bianca anche nell\'oscurità totale.' },
    ],
    actions: [
      { name: 'Multiattacco', desc: 'Il custode esegue tre attacchi con il pugno siderale.' },
      { name: 'Pugno Siderale', desc: 'Attacco con Arma da Mischia: +12 per colpire, raggio 3 m, un obiettivo. Colpito: 19 (3d8 + 6) danni contundenti più 7 (2d6) danni radianti.' },
      { name: 'Raggio Stellare (Ricarica 5–6)', desc: 'Il custode emette un raggio di energia stellare lungo una linea di 18 m e larga 1,5 m. Ogni creatura in quell\'area deve effettuare un tiro di salvezza su Destrezza con CD 18, subendo 36 (8d8) danni radianti in caso di fallimento, o la metà dei danni in caso di successo.' },
    ],
    legendary_actions: [
      { name: 'Colpo Rapido', desc: 'Il custode esegue un attacco con il pugno siderale.' },
      { name: 'Passo Stellare', desc: 'Il custode si teletrasporta magicamente, insieme a qualsiasi equipaggiamento indossato o trasportato, in uno spazio libero che può vedere entro 9 m.' },
      { name: 'Onda Celeste (Costa 2 Azioni)', desc: 'Il custode rilascia un\'onda di energia stellare. Ogni creatura entro 4,5 m da esso deve superare un tiro di salvezza su Costituzione con CD 16 o essere Stordita fino alla fine del suo turno successivo.' },
    ],
    reactions: [],
    environments: ['sotterraneo', 'planare', 'montagna'],
    image_url: null,
    description: 'Eretto a guardia di rovine sepolte sotto un cratere meteoritico, il custode delle rovine stellari è un costrutto antico forgiato per proteggere un segreto che nemmeno il suo creatore osò scrivere. Si muove con lentezza solenne ma reagisce con la velocità della luce stellare a qualunque intrusione. Creatura di taglia Enorme, di tipo costrutto, di allineamento legale neutrale. Grado di Sfida 12.',
  },
];

export const HOMEBREW_ITEMS = [
  {
    id: 'hb-item-fibbia-del-passo-silenzioso',
    name: 'Fibbia del Passo Silenzioso',
    category: 'Wondrous Items',
    rarity: 'common',
    attunement: 0,
    weight: 0.1,
    description: 'Oggetto meraviglioso, comune\n\nQuesta piccola fibbia in peltro, lavorata a forma di impronta felina, può essere fissata a una cintura, uno stivale o un mantello. Finché la indossi, hai vantaggio alle prove di Destrezza (Furtività) effettuate per muoverti silenziosamente, a condizione che tu non indossi armatura media o pesante.',
  },
  {
    id: 'hb-item-lente-dellindovino',
    name: 'Lente dell\'Indovino',
    category: 'Wondrous Items',
    rarity: 'uncommon',
    attunement: 1,
    weight: 0.1,
    description: 'Oggetto meraviglioso, non comune (richiede sintonia)\n\nQuesta lente monocolo dalla montatura di rame è incisa con minuscole rune divinatorie. Mentre la indossi, hai vantaggio alle prove di Intelligenza (Indagare) effettuate per individuare proprietà magiche di un oggetto o di un luogo. Una volta al giorno puoi guardare attraverso la lente e lanciare l\'incantesimo individuazione del magico senza spendere una spazio incantesimo né componenti.',
  },
  {
    id: 'hb-item-bracciale-di-marea-ferma',
    name: 'Bracciale di Marea Ferma',
    category: 'Wondrous Items',
    rarity: 'rare',
    attunement: 1,
    weight: 0.5,
    description: 'Oggetto meraviglioso, raro (richiede sintonia)\n\nIntagliato da un singolo pezzo di corallo pietrificato e legato con fili d\'argento, questo bracciale pulsa debolmente al contatto con l\'acqua salata. Mentre lo indossi, hai resistenza ai danni da freddo, puoi respirare sott\'acqua e la tua velocità di nuoto è pari alla tua velocità sul terreno. Inoltre, mentre sei immerso in acqua, hai vantaggio ai tiri di salvezza contro essere spinto, afferrato o trattenuto da correnti o creature acquatiche.',
  },
  {
    id: 'hb-item-tomo-delle-pagine-vuote',
    name: 'Tomo delle Pagine Vuote',
    category: 'Wondrous Items',
    rarity: 'very_rare',
    attunement: 1,
    weight: 3,
    description: 'Oggetto meraviglioso, molto raro (richiede sintonia da parte di un lanciatore di incantesimi)\n\nLe pagine di questo tomo rilegato in pelle scura appaiono completamente bianche finché non vi imprigioni un incantesimo. Quando ti sintonizzi con il tomo, puoi scegliere un incantesimo che conosci o hai preparato, di livello 5 o inferiore, e "scriverlo" nelle pagine spendendo uno spazio incantesimo del livello appropriato; l\'incantesimo appare come testo dorato luminescente. In seguito, puoi usare un\'azione per lanciare l\'incantesimo imprigionato dal tomo senza spendere uno spazio incantesimo né componenti materiali (a meno che non si consumino), usando il tuo modificatore di lancio incantesimi. Una volta lanciato in questo modo, le pagine tornano bianche e il tomo non può essere usato di nuovo finché non trascorre un\'alba.',
  },
  {
    id: 'hb-item-corona-dei-tre-inverni',
    name: 'Corona dei Tre Inverni',
    category: 'Wondrous Items',
    rarity: 'legendary',
    attunement: 1,
    weight: 1,
    description: 'Oggetto meraviglioso, leggendario (richiede sintonia)\n\nForgiata per un sovrano che regnò su tre inverni consecutivi senza concedere mai un\'alba di disgelo, questa corona di ferro brinato non si scalda mai al tocco. Mentre la indossi, hai resistenza ai danni da freddo e sei immune agli effetti ambientali del freddo estremo. Una volta per giorno puoi usare un\'azione per far emanare dalla corona un cono di gelo lungo 9 m: ogni creatura in quell\'area deve superare un tiro di salvezza su Costituzione con CD 16, subendo 45 (10d8) danni da freddo in caso di fallimento, o la metà dei danni in caso di successo.\n\n***Maledizione.*** La corona porta in sé l\'orgoglio gelido del suo primo sovrano. Mentre la indossi, hai svantaggio alle prove di Carisma che richiedano empatia, calore o compassione genuina, e i tuoi sogni sono visitati da inverni che non hai mai vissuto.',
  },
  {
    id: 'hb-item-cuore-del-crogiolo-primordiale',
    name: 'Cuore del Crogiolo Primordiale',
    category: 'Wondrous Items',
    rarity: 'artifact',
    attunement: 1,
    weight: 2,
    description: 'Oggetto meraviglioso, artefatto (richiede sintonia)\n\nQuesto cristallo a forma di cuore, caldo come brace viva, è ciò che resta del nucleo di un elementale del fuoco primordiale annientato all\'alba dei tempi. Pulsa lentamente come un battito cardiaco e illumina di luce arancione qualunque stanza buia.\n\nMentre sei sintonizzato con il cuore, sei immune ai danni da fuoco e i tuoi incantesimi che infliggono danni da fuoco infliggono 1d6 danni da fuoco aggiuntivi. Una volta per giorno puoi usare un\'azione per far detonare il cuore in una nova di fiamme: ogni creatura entro 6 m da te, escluso te stesso, deve superare un tiro di salvezza su Destrezza con CD 18, subendo 66 (12d10) danni da fuoco in caso di fallimento, o la metà dei danni in caso di successo.\n\n***Difetto Primordiale.*** Il cuore contiene ancora una scintilla della furia dell\'elementale distrutto. Ogni volta che termini un riposo lungo mentre sei sintonizzato con il cuore, tira un d20: con un risultato di 1, il cuore detona spontaneamente, infliggendo l\'effetto della nova di fiamme centrata su di te, calcolando il tiro di salvezza con CD 18 per ogni altra creatura nel raggio.\n\n***Distruzione.*** Il cuore del crogiolo primordiale può essere distrutto solo gettandolo nel cuore di un vulcano attivo durante un\'eruzione, mentre chi lo getta rinuncia ad alta voce a ogni pretesa di potere sul fuoco. In quel momento il cuore si dissolve in cenere e l\'eruzione si placa innaturalmente in pochi istanti.',
  },
];
